baseURL: https://allinleeyl.github.io/
languageCode: en-us
title: Yilin Li
theme: PaperMod
enableRobotsTXT: true
enableInlineShortcodes: true
params:
  env: production
  title: Lee
  label: 
    icon: "bird-svgrepo-com.svg"
    text: "Yilin Li"
  description: This is Yilin Li's homepage.
  defaultTheme: auto
  social: true
  ShowToc: false
  hideSummary: false
  taxonomies:
    category: categories
    tag: tags
    series: series
  education:
    - name: University of Groningen
      url: https://www.rug.nl/?lang=en
      period: 2026 - Present
      logo: "rug_logo.svg"
      type: PhD
    - name: University of Chinese Academy of Sciences
      url: https://english.ucas.ac.cn
      period: 2022 - 2025
      logo: ucas_logo.png
      type: MSc
    - name: Nankai University
      url: https://en.nankai.edu.cn/
      period: 2018 - 2022
      logo: "nku_logo.svg"
      type: BSc
  profileMode:
    enabled: true
    imageUrl: "https://images.unsplash.com/profile-1763801302802-a88de33d492dimage?w=150&dpr=2&crop=faces&bg=%23fff&h=150&auto=format&fit=crop&q=60&ixlib=rb-4.1.0" # optional
    Content: >
      Hi, ðŸ‘‹


      I am a PhD student in CogniGron group at the University of Groningen. My recent research focuses on **secure neuromorphic computing**. 

      Before that, my research entailed program analysis and [coarse-grained reconfigurable array (CGRA)](https://github.com/AllinLeeYL/CGRA-Tool). 
      
      
      Outside of work, I enjoys swimming, bycicling in the cities, and photographing.
  
  socialIcons:
    - name: github
      title: View Yilin's Github homepage
      url: https://github.com/AllinLeeYL
    - name: googlescholar
      title: View Yilin's Google Scholar profile
      url: https://scholar.google.com/citations?user=T0IQqpYAAAAJ&hl=en
menus:
  main:
    - name: Bio
      url: /
      weight: 10
    - name: Research
      url: research/
      weight: 20
    - name: Experience
      url: experience/
      weight: 30
    - name: Blog
      url: posts/
      weight: 40
  post:
    - name: Bio
      url: /
      weight: 10
    - name: Posts
      url: posts/
      weight: 20
    - name: Tags
      url: tags/
      weight: 30
    - name: Archive
      url: archives/
      weight: 40
caches:
  images:
    dir: :cacheDir/images
